# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['term_extractor_gui.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.json', '.'),
        ('term_extractor.py', '.'),
        ('data_preprocessor.py', '.'),
        ('json_utils.py', '.'),
        ('check_dependencies.py', '.'),
        ('fix_excel_dependencies.py', '.'),
    ],
    hiddenimports=[
        'pandas', 
        'numpy', 
        'openpyxl', 
        'xlrd', 
        'xlsxwriter', 
        'requests', 
        'zhipuai', 
        'json_repair', 
        'tqdm',
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.scrolledtext',
        'tkinter.simpledialog',
        'threading',
        'queue',
        'logging',
        'datetime',
        'pathlib',
        'shutil',
        're',
        'subprocess',
        'traceback',
        'json',
        'time',
        'sys',
        'os',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='术语提取工具',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,  # 如有图标，请指定路径
)
